export  const ActionTypes = {
    SET_BEVERAGES: "SET_BREEDS",
    SELECTED_BEVERAGE: "SELECTED_BEVERAGE",
    FILTERED_BEVERAGE_LIST: "FILTERED_BEVERAGE_LIST",
    SET_CHEESES: "SET_CHEESE",
    SELECTED_CHEESE: "SELECTED_CHEESE",
    FILTERED_CHEESE_LIST: "FILTERED_CHEESE_LIST",
}